version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    networks:
      - back
  backend:
    container_name: backend
    build: ./fairs-api
    depends_on:
      - redis
      - db
    env_file: .env
    networks:
      - back
    volumes:
      - ./fairs-api/src:/code/src
      - ./assets:/code/assets
  db:
    image: postgres:alpine
    env_file: .env
    networks:
      - back
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./nginx/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/usr/share/nginx/html/assets
    ports:
      - "80:80"
    networks:
      - back

networks:
  back:
